

services:
  db:
    image: mysql:5.7  # 使用するMySQLのイメージを指定
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: django-db
      MYSQL_USER: django
      MYSQL_PASSWORD: django
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

  web:
    build: .  # 現在のディレクトリ（Dockerfile）を基にイメージをビルド
    command: python3 manage.py runserver 0.0.0.0:8000  # Djangoの開発サーバーを起動
    volumes:
      - .:/code  # ホストのカレントディレクトリをコンテナの /code にマウント
    ports:
      - "8000:8000"  # ホストのポート8000をコンテナのポート8000にマッピング
    depends_on:
      - db  # dbサービスが先に起動するように指定
